asyncapi/glee

src/cli/index.js

The `npm run dev` command was failing to reload the development server when a file changes.

fix: npm run dev not reloading when file changes

---

src/lib/adapter.js

So far, Glee has been relying on the `x-servers` extension to link channels with servers. I'm now defaulting to the 2.2.0 channel servers feature instead of the `x-servers` extension.

feat: read channel.servers before falling back to x-servers

---

src/index.js
src/lib/configs.js

I was trying to run the `dummy` example uncommenting the lines here: https://github.com/asyncapi/glee/blob/master/examples/dummy/glee.config.js and found it's not loading the configuration.
This PR is fixing the configuration loader.

fix: glee.config.js is not being loaded into config object

---

examples/dummy/functions/onUserSignedUp.ts
src/lib/functions.ts

- Removed broadcast option while sending messages. Only send and reply are available, as mentioned [here](https://github.com/asyncapi/glee/issues/192#issuecomment-978165400).
Resolves #192

feat: made message sending api dry

---

package-lock.json
package.json

This PR removes the unused node-ipc dependency.

fix: remove node-ipc dependency

---

docs/functions.md

- Functions documentation shows that we can use the broadcast key in the returned object but that's not the case anymore.
- Removed the broadcast key from functions.md file
Fixes #271

chore: removed broadcast section from functions.md

---

examples/social-network/notifications-service/README.md
examples/social-network/websocket-server/README.md
mlc_config.json

this PR is supposed to fix all the [broken links](https://github.com/asyncapi/go-watermill-template/runs/6143307572?check_suite_focus=true) in markdown files across the repo.
- ignoring https://github.com/asyncapi/glee/blob/086c449/src since there are lots of links to this location and checking these links causes GitHub to give 429 (Too many requests) error.
- ignoring https://asyncapi.org/glee/docs for now. I guess we are going to have the docs on the website in the future?

docs: fix links in Markdown files

---

src/adapters/mqtt/index.ts

TypeScript compilation is failing. I'm casting this object as any for the lack of a better alternative right now.

fix: typescript error in MQTT adapter

---

src/lib/util.ts

Remove duplicate import statement for GleeMessage.js
Resolves #338

fix: remove duplicate import statements

---

src/adapters/ws/server.ts

This is a quick fix for #436, where we are not resolving it and treating it as an object. 
Fixing this is tricky as any part of the config object could be a function or an object, so it is hard to figure out which object to resolve and which not to. Something to consider for https://github.com/asyncapi/glee/issues/392
Fixes #436

fix: stop resolving config for ws server.

---

package-lock.json
package.json

So according to https://github.com/asyncapi/parser-js#testing-with-jest we need to add some `moduleMapper` rule to our `package.json` file since we are using parser.js and there is an issue with jest and spectral where jest is unable to understand package exports. 
This is causing these PRs to fail.
- https://github.com/asyncapi/glee/pull/465
- https://github.com/asyncapi/glee/pull/464
- https://github.com/asyncapi/glee/pull/463

fix: issue with spectral and jest

---

src/adapters/mqtt/index.ts

- Better MQTT logging, for subscription on topics
- More logging suggestions welcome
Resolves #406

feat: add better logging for mqtt

---

src/adapters/http/client.ts
src/adapters/kafka/index.ts
src/adapters/mqtt/index.ts
src/adapters/ws/client.ts

Resovles https://github.com/asyncapi/glee/issues/476#issuecomment-1672672495
cc: @SrijanShovit @Souvikns @peter-rr

feat: add type safety to adapters auth

---

docs/config-file.md

The `docs` key is missing in one of the documentation paragraphs. I'm also taking the opportunity to group keys by "glee-related" stuff and protocols.
No issue

docs: add missing docs key to config file document

---

test/lib/adapter.test.ts

PR aims to remove unused imports of import of 'MiddlewareCallback' from tests/lib/adapter.test.ts directory
Fixes #527

fix: removes Unused Imports Closes #527

---

src/lib/docs.ts

- This PR fixes #461
- Added `{ forceWrite: true }` in [https://github.com/freakfan15/glee/blob/461-generating-docs-fails-if-project-is-git-repo/src/lib/docs.ts](url) while creating the generator object.
- This will override the docs everytime, `npm run start` is run.
- Tested this by doing the same change in node modules of a new glee project and now it runs without any error every time.

fix: #461 Generating docs fails if project is a git repository

---

docs/pages/env-vars-config.md

This PR formats glee app structure and fixes rendering issues on website.
* Part of #480

fix: modifies glee structure format

---

docs/pages/crypto-websockets-interactive.md

This PR introduces interactive example reference for glee features.
* Part of #480

docs: adds an interactive tut ref for killercoda env

---

.github/workflows/update-docs-in-website.yml

This PR ensures to always have a clean and empty state of glee docs folder in website and supports for img files.
* Part of #480

fix: adjust github action for a file name changed preventing duplications

---

.github/workflows/update-docs-in-website.yml

Due to some caveats, selection of combination of filenames in the pipeline job might confuse the github workflow. Or might be this `rm -r ./pages/docs/tools/glee`

fix: removes combination of files options

---

src/adapters/mqtt/index.ts
src/lib/functions.ts
tsconfig.json

- fix the bug when Glee sends the message to the channel name instead of the channel address in MQTT.
- show a warning when the channel name is invalid when we send a message.
- show a warning when there is no send operation defined in the AsyncAPI file.
fixes #721

fix: send messages to the address of the channel

---

src/adapters/ws/client.ts

- Updated the current error message for more clear error debug.
Fixes: #688

fix: error message on missing auth function

---

src/adapters/ws/server.ts

- Fixed so that connections can be made even if there is a trailing slash when accessing the WebSocket API.
Fixes #713

fix: error when trying to access the Websocket API if pathname contains trailing slashes.

---

examples/http-test/asyncapi.yaml
examples/http-test/docs/asyncapi.md

This PR will modify some `operations/messages` in 'examples/http-test/asyncapi.yaml', which are not pointing to the correct channel.
Relates to https://github.com/asyncapi/glee/issues/476

fix: incorrect operation messages in 'examples/http-test/asyncapi.yaml'

---

.github/workflows/release-with-changesets.yml

chore: final final release

---

.github/workflows/release-with-changesets.yml

Installing the changelog package with pnpm instead of npm. I tried the rest of the steps locally and they work. Is this the last try? 😅

chore: install changelog with pnpm instead

---

.changeset/tame-clouds-turn.md
packages/kafka-adapter/package.json
packages/mqtt-adapter/package.json
packages/redis-cluster-adapter/package.json
packages/shared-utils/package.json
packages/socket.io-adapter/package.json
packages/web-adapter/package.json
packages/web-server-adapter/package.json

Yay! The release worked. However, some packages are not marked as public and therefore couldn't be published to npm. Fixing it here.

chore: publish as public packages
