.github/workflows/if-nodejs-pr-testing.yml, .github/workflows/if-nodejs-version-bump.yml, package.json
=> chore: revert fix: remove assets generation gh action

src/cli/index.js
It looks like it's causing problems in Heroku.
=> fix: remove params from shebang

src/lib/adapter.js
Change variable name as the variable name `server` is already declared in upper scope
Fixes #114
=> refactor: use different variable name in local scope

src/adapters/ws/index.js
Fixes a bug happening with `broadcast` method.
=> fix: bug with broadcast

src/lib/functions.ts
- added check and log for invalid data returned from functions
Fixes #270
=> fix: added log for invalid returned data from functions

test/errors/glee-error.test.ts, test/lib/message.test.ts, test/lib/router.test.ts, test/lib/util.test.ts, test/middlewares/buffer2string.test.ts, test/middlewares/existsInAsyncAPI.test.ts, test/middlewares/json2string.test.ts, test/middlewares/string2json.test.ts, test/middlewares/validate.test.ts, test/middlewares/validateConnection.test.ts
- Added more unit tests
Resolves #235
=> chore: added more tests

src/lib/logger.ts
Refactor nested template literals.
- ...
- ...
- ...
Fixes #337
=> refactor: remove nested template literals (#337)

src/adapters/mqtt/index.ts
Changed substr() to slice()
"
Fixes #336
=> fix: changed substr to slice (#336)

mlc_config.json
A quick fix for links that need to be ignored.
=> chore: fix link ignoring pattern

docs/config-file.md, examples/dummy/asyncapi.yaml, examples/dummy/glee.config.js, examples/dummy/package-lock.json, src/adapters/mqtt/index.ts, src/adapters/socket.io/index.ts, src/adapters/ws/index.ts, src/lib/adapter.ts, src/lib/index.d.ts, src/registerAdapters.ts, test/lib/glee.test.ts
This PR is updating the `glee.config.js` file to support configuration for multiple protocols.
- users can pass mqtt authentication parameters now from `glee.config.js` file instead of env variables. 
- users can now pass HTTP authentication token from `glee.config.js` file wich will be helpful for #319 
Fixes #347
=> feat: update glee config to support multiple protocols

src/lib/functions.ts
Functions may or may not return. We have to accept functions that return undefined or do not return.
=> fix: functions may not return

src/lib/configs.ts
Checks if ``glee.config.ts`` or ``glee.config.js`` exist. Prefers ``glee.config.ts`` if both exist.
Resolves #375
=> feat: add support for js and ts glee config file

CODEOWNERS
After chatting with @jonaslagoni, we've decided he will no longer be a code owner. Thanks for helping Glee grow, mate!
=> chore: say goodbye to Jonas as code owner

src/adapters/mqtt/index.ts
=> fix: connection fails in MQTT when port is specified

package.json
- Just read https://github.com/asyncapi/.github/issues/205 and I think it's time to use the new way of releasing and getting the workflows.
=> chore: use the new release format

package-lock.json, package.json
- Upgraded typedoc from 0.22.10 -> 0.23.28
- Upgraded eslint-plugin-sonarjs from 0.5.0 -> 0.18.0
- Upgraded package-lock.json file to use lockFileVersion 2.
=> fix: upgrade package versions

src/adapters/http/client.ts, src/adapters/mqtt/index.ts, src/cli/index.ts, src/docs.ts, src/index.ts, src/lib/docs.ts, src/lib/glee.ts, src/lib/util.ts
This PR aims to resolve all the bugs and code smells thrown by Sonarcloud. 
Fixing it for #430
=> refactor: resolve sonarcloud bugs

README.md
Currently, Readme is outdated and since things have changed, we are updating the docs. Even though Glee is still not version 1 yet, we can now use it for production, and this PR is updating the repository for that.
=> feat: remove under development from documentation

src/index.ts
As mentioned in #475, this PR adds the server url in the server ready logs.
Closes #475
=> feat: server ready logs show server url

docs/app-structure.md
Fixes minor correction in the topic sentence.
Part of #483
=> docs: replace deprecated glee cmd with asyncapi cli

package-lock.json, package.json, src/lib/asyncapiFile.ts, src/lib/functions.ts
Resolves #545 
Blocked by #523
=> feat: better error handling

.all-contributorsrc
=> fix: do not skip ci for allcontributors

examples/dummy/asyncapi.yaml, examples/dummy/package-lock.json, jest.config.js, src/adapters/ws/server.ts, src/middlewares/existsInAsyncAPI.ts, test/middlewares/existsInAsyncAPI.test.ts
- check if the message channel exists and has the appropriate operation.
- upgrade the dummy example to v3
- rewrite the tests for middleware.
- fix a small bug in the WebSockets server adapter.
fixes #558
=> feat: show an error when no operation is defined

docs/pages/application-structure/env-vars-config.md, examples/dummy/glee.config.js, examples/dummy/package-lock.json, src/index.ts, src/lib/configs.ts, src/lib/index.d.ts, src/lib/logger.ts, src/middlewares/channelLogger.ts, src/middlewares/payloadLogger.ts
- add the config to disable message logs.
fixes #557
=> feat: support message logging configuration

src/adapters/mqtt/index.ts
fixes: https://asyncapi.slack.com/archives/CQVJXFNQL/p1700146912926409
tested against: https://github.com/asyncapi/cli/tree/master/assets/create-glee-app/templates/tutorial
=> fix: mqtt adapter should subscribe to address

docs/pages/application-structure/env-vars-config.md, examples/http-test/functions/receiveTrigger.ts, src/adapters/http/server.ts, src/adapters/ws/server.ts, src/lib/adapter.ts, src/lib/functions.ts, src/lib/glee.ts, src/lib/index.d.ts, test/lib/adapter.test.ts, test/lib/glee.test.ts
The following improvements are introduced in this PR:
- better error handling. glee won't crush if unexpected errors occur.
- making sure it works great with the default example in CLI. (https://github.com/asyncapi/cli/pull/946)
- refactor the codebase to make it easier to maintain.
- remove the Websocket's redundant docs.
=> feat: improve websocket server Adapter

docs/pages/authentication.md, docs/pages/bearerToken.md, docs/pages/glee-template.md, docs/pages/httpApiKey.md, docs/pages/index.md, docs/pages/installation.md, docs/pages/intro-auth.md, docs/pages/userPassword.md
This PR fmts glee docs and fixes typos.
* Part of #480
=> refactor: formats glee docs

docs/pages/env-vars-config.md, docs/pages/function-lifecycle-events.md
This PR formats glee app structure and fixes typos.
* Part of #480
=> fix: formats application struct

docs/pages/authentication.md, docs/pages/bearerToken.md, docs/pages/glee-auth-intro.md, docs/pages/httpApiKey.md, docs/pages/userPassword.md
This PR modifies glee docs misspelled and fixes typos.
* Part of #480
=> fix: rectify the glee feats

docs/pages/env-vars-config.md, docs/pages/function-lifecycle-events.md
This PR adds extra line to fix rendering issue of a table and minor typos.
* Part of #480
=> fix: add extra line to fix rendering issue

src/index.ts
Fix the error where Glee Throws error when trying to pars .env.
=> fix: loading .env error

.github/workflows/update-docs-in-website.yml
See https://github.com/asyncapi/website/pull/2938
=> chore(ci): change pages to markdown

docs/pages/bearerToken.md, docs/pages/installation.md
ref: https://github.com/asyncapi/website/pull/3111/
=> fix: fixing rendering errors of glee docs

.changeset/blue-carpets-kneel.md
As previous release failed, I'm trying to release this time.
=> chore: release packages using pnpm and changesets

.changeset/mighty-parrots-join.md, .github/workflows/release-with-changesets.yml
=> chore: release round 2

.github/workflows/release-with-changesets.yml
Decided to go for `pnpm install --frozen-lockfile` instead of npm ci. Let's hope for the best.
=> chore: final release lol

.github/workflows/release-with-changesets.yml
This must be kidding with me 😅
=> chore: release using Node.js v20

packages/web-adapter/http.ts
Turns out the build was broken 😅
=> chore: fix build

.github/workflows/release-with-changesets.yml
LOL, this is like the machine is making fun of me today 😂
=> chore: install dep on root
